name: Update Jira Issues Fix Versions for Service Release

on:
  create:
    branches:
      - 'rc/[0-9]*'
      - 'hotfix/[0-9]*'
  push:
    branches:
      - 'rc/[0-9]+.[0-9]*'
      - 'hotfix/[0-9]+.[0-9]*'
    paths-ignore:
      - 'readme.md'
      - 'README.md'
      - 'LICENSE'

jobs:
  sync-service-versions-with-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Full Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Get tags
        run: git fetch --tags origin
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r https://raw.githubusercontent.com/reportportal/jira-versions-sync/main/requirements.txt
      - name: Sync versions
        run: python3 -c "$(wget -q -O - https://raw.githubusercontent.com/reportportal/jira-versions-sync/main/main_test.py)"
        env:
          JIRA_SERVER: ${{ vars.JIRA_SERVER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_FIX_VERSION: ${{ inputs.JIRA_FIX_VERSION }}
          LATEST_RELEASE_TAG: ${{ inputs.LATEST_RELEASE_TAG }}