name: Manual update Jira fix versions

on:
  workflow_dispatch:
    inputs:
      jira_fix_version:
        description: 'Jira Fix Version'
        required: true
      latest_release_tag:
        description: 'Latest Release Tag'
        required: true

jobs:
  manual-sync-service-versions-with-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Full Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r https://raw.githubusercontent.com/reportportal/jira-versions-sync/main/requirements.txt
      - name: Sync versions
        run: python3 -c "$(wget -q -O - https://raw.githubusercontent.com/reportportal/jira-versions-sync/main/main_test.py)"
        env:
          JIRA_SERVER: ${{ vars.JIRA_SERVER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_FIX_VERSION: ${{ inputs.jira_fix_version }}
          LATEST_RELEASE_TAG: ${{ inputs.latest_release_tag }}